---
- hosts: all
  connection: local

  collections:
    - cyberark.pas

  tasks:

    - name: Logon to CyberArk Vault using PAS Web Services SDK
      cyberark_authentication:
        api_base_url: "https://components.cyberark.local"
        validate_certs: false
        username: "bizdev"
        password: "Cyberark1"

    - name: Disabling a CyberArk User
      cyberark_user:
        username: "simon"
        disabled: true
        cyberark_session: "{{ cyberark_session }}"
      register: cyberarkaction
        
    - name: Debug message
      debug:
        var: cyberarkaction


    - name: Logoff from CyberArk Vault
      cyberark_authentication:
        state: absent
        cyberark_session: "{{ cyberark_session }}"
