- hosts: all
  connection: local
  tasks:
  - debug:
      msg: "Error: you been suspended due to too many tries or login from unauthorized station. We will reactivate your account now"
  - name: unsuspend-user
    ansible.builtin.uri:
      url: https://components.cyberark.local/PasswordVault/api/Users/55/Activate
      method: POST
      headers:
        Authorization: NzA1YWQ5MGUtZGRmNy00YzZkLTkyMmQtZTJlMzM5ZTFkZjMwOzhDNkUyMzQzN0I5QkMzQjAzNEJEMjFGNTcxNEE1QTA3MjgxNjk3RkU3MzU4MEM2RTYwOURCRUQ1NkNGRjZGNTI7MDAwMDAwMDIyRDQyQTk0QTkzNjY2ODE4MEY0NTY4MEYwMzI2NjI5NTE0MzE1Mzk3QTY4NTdBRTMwRTI4RjI5QTAxRTg2RjkxMDAwMDAwMDA7
        Content-Type: application/json
        Content-Length: 0
      validate_certs: false
