---
- name: Demo rules with kafka as source
  hosts: localhost 
  sources:
    - name: cyberark.eda.kafka
      ansible.eda.kafka:
        topic: ansible 
        host: localhost 
        port: 9092
  rules:
    - name: Check defined
      condition: event.output is defined
      action:
        print_event:
          var_root: output
    - name: debug
      enabled: False
      condition: event.payload is defined
      action:
        debug:
