- name: Demo rules with kafka as source
  hosts: localhost 
  sources:
    - cyberark.eda.kafka:
        topic: ansible 
        host: localhost 
        port: 9092
  rules:
    - name: Check defined
      condition: event.body.format == "ansible"
      action:
        print_event:
          var_root: body

    - name: stop
      condition: event.body == "stop"
      action:
        shutdown:
